security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: 'auto'
        App\Entity\Administrator: 'auto'
    providers:
        doctrine_user:
            entity:
                class: App\Entity\User
                property: email
        doctrine_administrator:
            entity:
                class: App\Entity\Administrator
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            stateless: true
            pattern: ^/api
            provider: doctrine_user
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
        admin:
            pattern: ^/admin
            provider: doctrine_administrator
            form_login:
                login_path: admin_security_login
                check_path: admin_security_login
            logout:
                path: admin_security_logout

    access_control:
        # - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        # - { path: ^/api/login, roles: PUBLIC_ACCESS }
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/security/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }